---
- name: Assert that vars are defined
  assert:
    that:
      - gitlab_container_hostname is defined

- name: Install pip docker
  pip:
    name: docker

- name: Create the Gitlab dirs
  file:
    state: directory
    path: '{{ gitlab_dir }}/{{ item }}'
    recurse: true
  loop:
    - config
    - logs
    - data

- name: Copy gitlab.rb
  copy:
    content: '{{ gitlab_rb }}'
    dest: '{{ gitlab_dir }}/config/gitlab.rb'

- set_fact:
    gitlab_container: '{{ gitlab_container_defaults | combine(gitlab_container)}}'

- name: Pull the docker image
  docker_image:
    source: pull
    name: '{{ gitlab_container.image }}'
    force: true

- name: Start the docker container
  docker_container: '{{ gitlab_container }}'

- name: Wait for Gitlab to start
  register: health_check_result
  shell: >-
    docker exec {{ gitlab_container.name }}
    bash -c 'curl --fail localhost/-/readiness?all=1'
  retries: 180
  delay: 1
  until: health_check_result.rc == 0
