---
- name: Assert that vars are defined
  assert:
    that:
      - gitlab_container_hostname is defined

- name: Install pip docker
  pip:
    name: docker

- name: Create the Gitlab dirs
  file:
    state: directory
    path: '{{ gitlab_dir }}/{{ item }}'
    recurse: true
  loop:
    - config
    - logs
    - data

- name: Copy gitlab.rb
  copy:
    content: '{{ gitlab_rb }}'
    dest: '{{ gitlab_dir }}/config/gitlab.rb'

- name: Pull the docker image
  docker_image:
    source: pull
    name: '{{ gitlab_image }}'
    force: true

- name: Start the docker container
  docker_container:
    comparisons:
      '*': strict
    image: '{{ gitlab_image }}'
    name: '{{ gitlab_container_name }}'
    restart_policy: unless-stopped
    networks: '{{ gitlab_docker_networks }}'
    ports: '{{ gitlab_container_ports }}'
    hostname: '{{ gitlab_container_hostname }}'
    volumes:
      - '{{ gitlab_dir }}/config:/etc/gitlab'
      - '{{ gitlab_dir }}/logs:/var/log/gitlab'
      - '{{ gitlab_dir }}/data:/var/opt/gitlab'

- name: Wait for Gitlab to start
  register: health_check_result
  shell: >-
    docker exec {{ gitlab_container_name }}
    bash -c 'curl --fail localhost/-/readiness?all=1'
  retries: 180
  delay: 1
  until: health_check_result.rc == 0
