---
- name: Health check Gitlab
  listen: health_check_gitlab
  register: health_check_result
  shell: >-
    docker exec {{ gitlab_container_name }}
    bash -c 'curl --fail localhost/-/readiness?all=1'
  retries: 180
  delay: 1
  until: health_check_result.rc == 0
