---
- name: Converge
  hosts: gitlab
  vars:
    ansible_become: true
  tasks:
    - name: Install docker-py
      pip:
        name: docker

    - name: Create network
      docker_network:
        name: test_gitlab

    - name: Deploy Gitlab
      include_role:
        name: ansible-role-gitlab
