---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: gitlab
    vpc_subnet_id: subnet-1efffb7b
    image: ami-0c48db26521ca9f07
    instance_type: m5.xlarge
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      host_key_checking: false
      pipelining: true
  inventory:
    group_vars:
      all:
        gitlab_dir: /tmp/gitlab
        gitlab_container_hostname: gitlab.xyz
        gitlab_docker_networks:
          - name: test_gitlab
verifier:
  name: testinfra
  directory: ../../tests
  options:
    reruns: '3'
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
